# Generated by Django 4.2.1 on 2023-05-31 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('IdEspecialidad', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('IdDocente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Apellido', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('FIngreso', models.DateField(auto_now_add=True)),
                ('Dni', models.CharField(max_length=8)),
                ('Telefono', models.IntegerField()),
                ('Curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.curso')),
            ],
        ),
    ]
