# Generated by Django 4.2.1 on 2023-05-31 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_especialidad_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('IdMatricula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Fechamat', models.DateField()),
                ('Cuotas', models.IntegerField()),
                ('IdCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.curso')),
            ],
        ),
    ]
